### ISSUE TITLE
functions.php kaputt

### ISSUE THREAD

**Issue by rosario-raulin** [kre8tiv/Joseph-knows-best#1]
Die functions.php scheint kaputt zu sein. Nach Installation des Themes gibt es einen Fehler:

```
2016/08/28 15:45:35 [error] 2609#2609: *16916 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected end of file in /var/www/xxxxxxxx/wp-content/themes/Joseph-knows-best-master/functions/theme-functions.php on line 804"
```

Getestet mit WordPress 4.6 und PHP 7.0.8.

**Comment by rosario-raulin** [comment]
Fehler scheint mit PHP 7 zusammenzuhängen, Ursache ist noch unbekannt. Mit PHP 5.x tritt der Fehler nicht auf.

**Comment by Deltachaos** [comment]
Short open tags gibt es mit PHP7 nicht mehr. Fix in PR #2

**Comment by kre8tiv** [comment]
Fixed, thanks!
